# install-services.yml
---
  - hosts: loadbalancers
    become: true
    tasks:
      - name: Installing apache apache2
        apt:
          name: apache2
          state: present
      - name: Ensure apache starts
        service: 
          name: apache2 
          state: started 
          enabled: yes
     
  - hosts: webservers
    become: true
    tasks: 
      - name: Instaling services
        apt:
          name:
            - apache2
            - php
      - name: Ensure apache starts
        service: 
          name: apache2 
          state: started 
          enabled: yes      