#setup-lb.yml
---
  - hosts: loadbalancers
    become: true
    tasks:
      - name: Create template
        template:
          src: /Users/amarenderreddydodle/ansible0/config/lb-config.j2
          dest: /etc/apache2/sites-available/lb.conf
          mode: 064
        notify: restart apache2
      
    handlers: 
      - name: restart apache2
        service: name=apache2 state=restarted